#!/usr/bin/env python3

import subprocess
import pandas as pd
import matplotlib.pyplot as plt

# simulate Faital 12PR320:
subprocess.run([
    "speacoupy",
    "config_ventedbox.yaml",
    "--csv",
    "--pdf",
    "--prefix", "SpeAcouPy_output"
])
subprocess.run([
    "speacoupy",
    "config_ventedbox.yaml",
    "--radiators", "driver_front"
    "--csv",
    "--prefix", "SpeAcouPy_output_driver-front"
])


### IMPEDANCE: COMPARE WITH VITUIX SIMULATED CURVE

# load simulated data:
faital_sim = pd.read_csv("SpeAcouPy_output_DATA.csv", sep=",", comment="#")

# load Vituix impedance curve:
faital_vituix_Z = pd.read_csv("Faital12PR320-OSMC-warm_Vituix_Impedance_ventedbox-52L-portL8cm-portD9.4cm.txt", sep="\t", comment="#")

# plot impedance curves and save to PDF:
plt.figure()
plt.plot(faital_sim["Frequency (Hz)"], faital_sim["Impedance Magnitude (Ω)"], label="SpeAcouPy simulation")
plt.plot(faital_vituix_Z["Frequency [Hz]"], faital_vituix_Z["Impedance Magnitude [ohm]"], label="Vituix CAD", linestyle="--")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Impedance (Ohm)")
plt.title("Impedance Faital 12PR320 in 52 L vented box")
plt.grid(True)
plt.legend()
plt.xscale("log")
plt.savefig("IMPEDANCE_COMPARISON.pdf", format="pdf")
plt.close()


### SPL: COMPARE WITH VITUIX SIMULATION

# load Vituix SPL curve:
faital_vituix_SPL = pd.read_csv("Faital12PR320-OSMC-warm_Vituix_SPL_ventedbox-52L-portL8cm-portD9.4cm-2pi.txt",sep="\t")

# plot SPL curves and save to PDF:
plt.figure()
plt.plot(faital_sim["Frequency (Hz)"], faital_sim["SPL (dB-SPL @ 1m / 2pi)"], label="SpeAcouPy")
plt.plot(faital_vituix_SPL["Frequency [Hz]"], faital_vituix_SPL["Total SPL 2pi [dB]"], label="Vituix CAD", linestyle="--")
plt.xlabel("Frequency (Hz)")
plt.ylabel("SPL (dB-SPL)")
plt.title("SPL Faital 12PR320 in 52 L vented box (1m/2pi)")
plt.grid(True)
plt.legend()
plt.xscale("log")
plt.savefig("SPL_COMPARISON.pdf", format="pdf")
plt.close()

