# simulation of a driver with its front radiating into free space and the back into a flared horn
# the speacoupy output does not perfectly agree with the AJ Horn output because AJ Horn uses a plane-wave approximation for the flared horn

radiation_space: 2pi

elements:

- type: horn
  label: HORN
  L: 2.5
  S_throat: 400E-4      # m²
  S_mouth:  3600E-4      # m²
  R_throat: 1
  R_mouth: 30
  profile: conical
  mouth_load: radiation_space
  mouth_label: HORN_MOUTH
  mouth_termination: baffle

- type: driver
  label: DRIVER
  fs: 35.0
  Vas: 60e-3
  Qms: 3.5
  Qes: 0.35
  Sd: 200E-4
  Re: 8.0
  Z_hf: [ [1E3,8.0] , [1E4,8.0]]
  front_load: radiation_space
  back_load: HORN
  front_radiator_label: DRIVER_FRONT
  back_radiator_label: DRIVER_BACK

circuit:
  series:
  - DRIVER

frequency:
  min: 10
  max: 2000
  points: 100

source:
  volts_rms: 2.83
