# simulation of a driver with its front radiating into a flared horn and the back into a closed chamber.

radiation_space: 2pi

elements:

- type: horn
  label: HORN
  L: 2.5
  S_throat: 200E-4      # m²
  S_mouth:  3600E-4    # m²
  R_throat: 0
  R_mouth: 0
  profile: exponential
  mouth_load: radiation_space
  mouth_label: HORN_MOUTH

- type: sealed_box
  label: CLOSEDCHAMBER
  Vb: 10E-3
  Rb: 1E5

- type: driver
  label: DRIVER
  fs: 35.0
  Vas: 60e-3
  Qms: 3.5
  Qes: 0.35
  Sd: 200E-4
  Re: 8.0
  Z_hf: [ [1E3,9.0] , [1E4,20]]
  front_load: HORN
  back_load: CLOSEDCHAMBER
  front_radiator_label: DRIVER_FRONT
  back_radiator_label: DRIVER_BACK

circuit:
  series:
  - DRIVER

frequency:
  min: 5
  max: 10000
  points: 300

source:
  volts_rms: 2.83
