# simulation of a driver with its front radiating into free space back into a horn

radiation_space: 2pi

elements:

- type: horn
  label: HORN
  L: 0.8
  S_throat: 200E-4      # m²
  S_mouth:  2000E-4      # m²
  profile: exponential
  mouth_load: radiation_space     # radiate into space
  mouth_label: HORN_MOUTH
  R_mouth: 0
  R_throat: 100

- type: sealed_box
  label: CLOSEDCHAMBER
  Vb: 10E-3
  Rb: 1E5

- type: driver
  label: DRIVER
  fs: 35.0
  Vas: 60e-3
  Qms: 3.5
  Qes: 0.35
  Sd: 200E-4
  Re: 8.0
  Z_hf: [ [1E3,9.0] , [1E4,20]]
  front_load: HORN
  back_load: CLOSEDCHAMBER
  front_radiator_label: DRIVER_FRONT
  back_radiator_label: DRIVER_BACK

circuit:
  series:
  - DRIVER

frequency:
  min: 5
  max: 10000
  points: 300

source:
  volts_rms: 2.83
