# simulation of a Faital 12PR320 woofer in a closed box. Woofer TSP as in validation/driver/...

radiation_space: 2pi

elements:

- type: sealed_box
  label: CLOSEDBOX
  Vb: 0.025     # m³  (50 liters internal volume)
  ### Rb: Inf      # mechanical resistance reflecting losses due to to leaks and stuffing with damping materials (Pa·s/m³). Note: Rb = Qb x rho x c² / 2pi / fb Vb
  Rb: 4.75E5    # Vituix: fb = 93.8 Hz, Ql = 100, Qa = 100 ==> Qb = 1/(1/Ql+1/Qa = 50 ==> Rb = 4.75E5

- type: driver
  label: WOOFER
  fs: 40.1
  Vas: 0.1133
  Qms: 11
  Qes: 0.42
  Sd: 0.0539
  Re: 5.4
  Z_hf: [ [1250,9.67] , [2500,14.45] , [5000,19.17] , [ 10238,29.4] , [ 20000,44.21] ]
  ### Z_hf: [ [5000,5.4] , [ 20000,5.4] ]
  front_load: radiation_space
  back_load: CLOSEDBOX
  front_radiator_label: driver_front
  back_radiator_label: driver_back

network:
  series:
  - WOOFER

frequency:
  min: 5
  max: 10000
  points: 300

source:
  volts_rms: 2.83
