# simulation of a Faital 12PR320 woofer in a closed box. Woofer TSP as in validation/driver/...

radiation_space: 2pi

elements:

- type: sealedbox
  label: closedbox
  Vb: 0.050     # m³  (50 liters internal volume)
  Qb: 100       # High value → mostly rigid, sealed enclosure

- type: driver
  label: Faital12PR320
  fs: 40.1
  Vas: 0.1133
  Qms: 11
  Qes: 0.42
  Sd: 0.0539
  Re: 5.4
  Z_hf: [ [1250,9.67] , [2500,14.45] , [5000,19.17] , [ 10238,29.4] , [ 20000,44.21] ]
  front_load: radiation_space
  back_load: closedbox
  front_radiator_label: driver_front
  back_radiator_label: driver_back

network:
  series:
  - Faital12PR320

frequency:
  min_hz: 20
  max_hz: 10000
  points: 300

source:
  volts_rms: 2.83
