radiation_space: 2pi

elements:
- type: driver
  label: Faital12PR320
  fs: 45
  Vas: 0.05
  Qms: 5.0
  Qes: 0.5
  Sd: 0.014
  front_load: radiation_space
  back_load: radiation_space
  front_radiator_label: driver_front
  back_radiator_label: driver_back
  Re: 6.0
  Z_hf: [ [508,9.37] , [1016 , 11.70] , [2031 , 15.05] , [4062 , 21.36] , [8123 , 32.05] ]

network:
  series:
  - Faital12PR320

frequency:
  min_hz: 20
  max_hz: 20000
  points: 800

source:
  volts_rms: 2.83
  distance_m: 1.0
