radiation_space: 4pi


elements:

  - type: driver
    label: Faital12PR320
    fs: 45        # resonance frequency [Hz]
    Vas: 0.05     # equivalent compliance volume [m^3]
    Qms: 5.0
    Qes: 0.5
    Sd: 0.014     # diaphragm area [m^2]
    front_load: radiation_space
    back_load: radiation_space

network:
  series:
    - Faital12PR320

frequency:
  min_hz: 20
  max_hz: 20000
  points: 800

source:
  volts_rms: 2.83
  distance_m: 1.0
