# simulation of the Faital 12PR320. Measurement data is the "warm" driver as described here: https://www.diyaudio.com/community/threads/open-source-monkey-box.327594/page-13#post-5586614
#
# parameters derived from this measurement: Rdc = 5.4; fs = 40.1; Qes = 0.42; Qms = 11

radiation_space: 2pi

elements:
- type: driver
  label: Faital12PR320
  fs: 40.1
  Vas: 0.1133
  Qms: 11
  Qes: 0.42
  Sd: 0.0539
  Re: 5.4
  Z_hf: [ [1250,9.67] , [2500,14.45] , [5000,19.17] , [ 10238,29.4] , [ 20000,44.21] ]
  front_load: radiation_space
  back_load: radiation_space
  front_radiator_label: driver_front
  back_radiator_label: driver_back

network:
  series:
  - Faital12PR320
frequency:
  min_hz: 5
  max_hz: 10000
  points: 300

source:
  volts_rms: 2.83
