THIS CONFIG FILE NEEDS ADJUSTING FOR THE NEW/SIMPLER WAY OF SPECIFYING THE ROOM LOADING



elements:

  - type: piston
    label: rad_front
    Sd: 0.014       # same as driver Sd
    loading: 4pi    # free space

  - type: piston
    label: rad_back
    Sd: 0.014
    loading: 4pi

  - type: Driver
    label: Faital12PR320
    fs: 45        # resonance frequency [Hz]
    Vas: 0.05     # equivalent compliance volume [m^3]
    Qms: 5.0
    Qes: 0.5
    Sd: 0.014     # diaphragm area [m^2]
    front_load: rad_front
    back_load: rad_back

network:
  series:
    - Faital12PR320

