#!/usr/bin/env python3

import subprocess
import pandas as pd
import matplotlib.pyplot as plt

# simulate Faital 12PR320:
subprocess.run([
    "speacoupy",
    "config_driver.yaml",
    "--radiators", "driver_front",
    "--csv",
    "--pdf",
    "--prefix", "SpeAcouPy_output_"
])

# load simulated data:
faital_sim = pd.read_csv("SpeAcouPy_output__DATA.csv", sep=",", comment="#")

# load measured impedance curve:
faital_msr = pd.read_csv("Faital_12PR320_impedance.txt", sep=r"\s+", comment="#", header=None)

# plot impedance curves and save to PDF:
plt.figure()
plt.plot(faital_sim["Frequency (Hz)"], faital_sim["Impedance Magnitude (Ω)"], label="SpeAcouPy simulation")
plt.plot(faital_msr[0], faital_msr[1], label="Measured")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Impedance (Ohm)")
plt.title("Impedance Faital 12PR320")
plt.grid(True)
plt.legend()
plt.xscale("log")
plt.savefig("IMPEDANCE_COMPARISON.pdf", format="pdf")
plt.close()
