# simulation of a driver with its front radiating into free space and the back into a single conical horn

radiation_space: 2pi

elements:

- type: horn
  label: CONICALHORN1
  L: 1
  S_throat: 200E-4      # m²
  S_mouth:  1800E-4      # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
  mouth_load: CONICALHORN2

- type: horn
  label: CONICALHORN2
  L: 1
  S_throat: 1800E-4      # m²
  S_mouth:  5000E-4      # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
  mouth_load: CONICALHORN3

- type: horn
  label: CONICALHORN3
  L: 1
  S_throat: 5000E-4      # m²
  S_mouth:  9800E-4      # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
  mouth_load: CONICALHORN4
  
- type: horn
  label: CONICALHORN4
  L: 1
  S_throat: 9800E-4      # m²
  S_mouth:  16200E-4      # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
  mouth_load: radiation_space
  mouth_label: CONICALHORN4
  mouth_termination: baffle

- type: driver
  label: DRIVER
  fs: 35.0
  Vas: 60e-3
  Qms: 3.5
  Qes: 0.35
  Sd: 200E-4
  Re: 8.0
  Z_hf: [ [1E3,8.0] , [1E4,8.0]]
  front_load: radiation_space
  back_load: CONICALHORN1
  front_radiator_label: DRIVER_FRONT
  back_radiator_label: DRIVER_BACK

circuit:
  series:
  - DRIVER

frequency:
  min: 10
  max: 2000
  points: 100

source:
  volts_rms: 2.83
