frequency:
  min_hz: 20
  max_hz: 20000
  points: 1600
elements:
- type: piston_wideband
  label: FREE_AIR_LOADING
  loading: 4pi
- type: driver
  label: woofer
  Re: 10
  Le: 0.00035
  front_load: FREE_AIR_LOADING
  back_load: FREE_AIR_LOADING
  Sd: 0.053
  fs: 50.329212104487034
  Vas: 0.397893153364
  Qms: 1.9764235376052368
  Qes: 0.5774794850563145
network:
- woofer
source:
  volts_rms: 2.83
  distance_m: 1.0
