
frequency:
  min_hz: 20
  max_hz: 20000
  points: 1600

driver:
  Re: 5.7
  Le: 0.00035
  Bl: 7.4
  Sd_m2: 0.053
  Rms: 1.6
  Mms: 0.020
  Cms: 0.0007

  front_load:
    type: piston_wideband
    loading: 2pi
  back_load:
    type: sealed
    Vb_l: 18

  angles_deg: [0, 15, 30, 45]

network:
  net:
    op: series
    parts:
      - re: { R: 1.0 }
      - driver: {}

source:
  volts_rms: 2.83
  distance_m: 1.0

room:
  loading: 2pi
