# simulation of a driver with its front radiating into radiation_space and the back into a straight transmission line (modelled as a straight "horn")

radiation_space: 2pi

elements:

- type: horn
  label: TRANSMISSIONLINE
  L: 2.5
  S_throat: 400E-4      # m²
  S_mouth:  400E-4      # m²
  R_throat: 0
  R_mouth: 0
  profile: exponential
  mouth_load: radiation_space
  mouth_label: LINE_MOUTH

- type: driver
  label: DRIVER
  fs: 35.0
  Vas: 60e-3
  Qms: 3.5
  Qes: 0.35
  Sd: 200E-4
  Re: 8.0
  Z_hf: [ [1E3,9.0] , [1E4,20]]
  front_load: radiation_space
  back_load: TRANSMISSIONLINE
  front_radiator_label: DRIVER_FRONT
  back_radiator_label: DRIVER_BACK

circuit:
  series:
  - DRIVER

frequency:
  min: 5
  max: 10000
  points: 300

source:
  volts_rms: 2.83
