
# Simple series network (back-compat with earlier examples)
frequency:
  min_hz: 15
  max_hz: 10000
  points: 1200

room:
  loading: 2pi   # 4pi | 2pi | 1pi | 1/2pi<

box:
  type: sealed
  Vb_l: 18

driver:
  Re: 6.2
  Le: 0.0004
  Bl: 7.1
  Sd_m2: 0.053
  Rms: 1.7
  Mms: 0.021
  Cms: 0.00065

series_network:
  - type: ce
    C: 0.000068
  - type: driver

source:
  volts_rms: 2.83
  distance_m: 1.0
