# Simple series network (updated: explicit front/back loads)
frequency:
  min_hz: 15
  max_hz: 10000
  points: 1200

driver:
  Re: 6.2
  Le: 0.0004
  Bl: 7.1
  Sd_m2: 0.053
  Rms: 1.7
  Mms: 0.021
  Cms: 0.00065

  front_load:
    type: piston_wideband
    loading: 2pi
  back_load:
    type: sealed
    Vb_l: 18

# Back-compat chain kept; driver sits in the series
series_network:
  - type: ce
    C: 0.000068
  - type: driver

source:
  volts_rms: 2.83
  distance_m: 1.0

room:
  loading: 2pi
