radiation_space: 2pi

elements:

- type: sealed_box
  label: CLOSEDBOX
  Vb: 0.025     # m³  (25 liters internal volume)
  Rb: 4.75E5    # mechanical resistance (Pa·s/m³)

- type: horn
  label: HORN
  L: 0.8               # length in meters
  S_throat: 0.005      # throat area in m²
  S_mouth: 0.15        # mouth area in m²
  profile: con         # conical profile
  mouth_load: radiation_space
  mouth_label: horn_mouth

- type: driver
  label: WOOFER
  fs: 40.1
  Vas: 0.1133
  Qms: 11
  Qes: 0.42
  Sd: 0.0539
  Re: 5.4
  Z_hf: [ [1250,9.67] , [2500,14.45] , [5000,19.17] , [10238,29.4] , [20000,44.21] ]
  front_load: HORN
  back_load: CLOSEDBOX
  front_radiator_label: driver_front
  back_radiator_label: driver_back

circuit:
  series:
  - WOOFER

frequency:
  min: 5
  max: 10000
  points: 300

source:
  volts_rms: 2.83

