# simulation of a driver with its front radiating into free space and the back into a straight transmission line (modelled as a straight "horn")

radiation_space: 2pi

elements:

- type: horn
  label: TRANSMISSIONLINE
  L: 2.5
  S_throat: 400E-4      # m²
  S_mouth:  400E-4      # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
  mouth_load: radiation_space
  mouth_label: LINE_MOUTH
  mouth_termination: baffle   # use 'free' if you want 4π (unbaffled) radiation

- type: driver
  label: DRIVER
  fs: 35.0
  Vas: 60e-3
  Qms: 3.5
  Qes: 0.35
  Sd: 200E-4
  Re: 8.0
  Z_hf: [ [1E3,8.0] , [1E4,8.0]]
  front_load: radiation_space
  back_load: TRANSMISSIONLINE
  front_radiator_label: DRIVER_FRONT
  back_radiator_label: DRIVER_BACK

circuit:
  series:
  - DRIVER

frequency:
  min: 10
  max: 3000
  points: 200

source:
  volts_rms: 2.83
