# testing the splitting of acoustical flows
# (A) single horn
# (B) chain of two horn sequences with same overall geometry, but second sequencs split in two identical halves.
# A and B should be identical at low frequencies, but may diverge slightly at higher frequencies due to two smaller pistons radiating in parallel

# consdier conical horn, 4 m long:
# S(x) = pi * (R0 * (x+x0)/x0)² with x0 = 1 and R0 = sqrt(S0/pi) = sqrt(200E-4/pi) = 7.9788E-2:
# x = 0: S =  200E-4
# x = 1: S =  800E-4
# x = 2: S = 1800E-4
# x = 3: S = 3200E-4
# x = 4: S = 5000E-4

radiation_space: 2pi

elements:

# single full horn for reference
- type: horn
  label: SINGLEHORN
  L: 4
  S_throat:  200E-4      # m²
  S_mouth:  5000E-4      # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
  mouth_load: radiation_space
  mouth_label: SINGLEHORN_MOUTH
  mouth_termination: baffle
  
# sequence of horns (1m + 2 x 3m split horn halves):
#First horn section on the driver, splitting in two
- type: horn
  label: SPLITTER
  L: 1
  S_throat: 200E-4      # m²
  S_mouth:  800E-4      # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
  mouth_load: [SPLIT1, SPLIT2]  # <-- split into two horns

- type: horn
  label: SPLIT1
  L: 3
  S_throat: 400E-4      # m²
  S_mouth:  2500E-4     # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
  mouth_load: radiation_space
  mouth_label: SPLIT1_MOUTH
  mouth_termination: baffle
 
- type: horn
  label: SPLIT2
  L: 3
  S_throat: 400E-4      # m²
  S_mouth:  2500E-4     # m²
  R_throat: 0
  R_mouth: 0
  profile: conical
#  mouth_load: radiation_space
  mouth_load: radiation_space
  mouth_label: SPLIT2_MOUTH
  mouth_termination: baffle
 

- type: driver
  label: DRIVER
  fs: 35.0
  Vas: 60e-3
  Qms: 3.5
  Qes: 0.35
  Sd: 200E-4
  Re: 8.0
  Z_hf: [ [1E3,8.0] , [1E4,8.0]]
  front_load: radiation_space
#  back_load: SPLITTER   # <--- use this for the split horn
  back_load: SINGLEHORN   # <--- use this for no split
  front_radiator_label: DRIVER_FRONT
  back_radiator_label: DRIVER_BACK

circuit:
  series:
  - DRIVER

frequency:
  min: 10
  max: 2000
  points: 300

source:
  volts_rms: 2.83
